"""init_db

Revision ID: 021c072ba7b5
Revises: 
Create Date: 2026-05-03 17:10:09.688711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '021c072ba7b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fcm_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_fcm_token'), 'users', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('firmwares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_type', 'version', name='uq_board_type_version')
    )
    op.create_index(op.f('ix_firmwares_board_type'), 'firmwares', ['board_type'], unique=False)
    op.create_index(op.f('ix_firmwares_id'), 'firmwares', ['id'], unique=False)
    op.create_index(op.f('ix_firmwares_is_active'), 'firmwares', ['is_active'], unique=False)
    op.create_table('homes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_id'), 'homes', ['id'], unique=False)
    op.create_index(op.f('ix_homes_owner_id'), 'homes', ['owner_id'], unique=False)
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_otps_email'), 'password_reset_otps', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_expires_at'), 'password_reset_otps', ['expires_at'], unique=False)
    op.create_table('access_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_cards_card_uid'), 'access_cards', ['card_uid'], unique=True)
    op.create_index(op.f('ix_access_cards_home_id'), 'access_cards', ['home_id'], unique=False)
    op.create_index(op.f('ix_access_cards_id'), 'access_cards', ['id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_id', 'floor_number', name='uq_home_floor_number')
    )
    op.create_index(op.f('ix_floors_home_id'), 'floors', ['home_id'], unique=False)
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('home_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='member_role'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_members_home_id'), 'home_members', ['home_id'], unique=False)
    op.create_index(op.f('ix_home_members_user_id'), 'home_members', ['user_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('board_type', sa.String(length=50), nullable=False),
    sa.Column('home_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('UNPAIRED', 'PAIRED', 'ONLINE', 'OFFLINE', name='board_status'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_home_id'), 'boards', ['home_id'], unique=False)
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.create_index(op.f('ix_boards_mac_address'), 'boards', ['mac_address'], unique=True)
    op.create_index(op.f('ix_boards_room_id'), 'boards', ['room_id'], unique=False)
    op.create_index(op.f('ix_boards_status'), 'boards', ['status'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=20), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('GRANTED', 'DENIED', 'UNKNOWN_CARD', name='access_result'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['access_cards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_board_id'), 'access_logs', ['board_id'], unique=False)
    op.create_index(op.f('ix_access_logs_created_at'), 'access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.Enum('RELAY', 'DHT11', 'PIR', 'LDR', 'RC522', 'CAMERA', 'DOOR_LOCK', name='device_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gpio', sa.Integer(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_board_id'), 'devices', ['board_id'], unique=False)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('device_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_history_created_at'), 'device_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_history_device_id'), 'device_history', ['device_id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_downsampled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_created_at'), 'sensor_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_sensor_data_device_id'), 'sensor_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_is_downsampled'), 'sensor_data', ['is_downsampled'], unique=False)
    op.create_table('timers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('target_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execute_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', 'CANCELLED', name='timer_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_device_id'), 'timers', ['device_id'], unique=False)
    op.create_index(op.f('ix_timers_execute_at'), 'timers', ['execute_at'], unique=False)
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    op.create_index(op.f('ix_timers_status'), 'timers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timers_status'), table_name='timers')
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_execute_at'), table_name='timers')
    op.drop_index(op.f('ix_timers_device_id'), table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_sensor_data_is_downsampled'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_device_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_created_at'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_device_history_device_id'), table_name='device_history')
    op.drop_index(op.f('ix_device_history_created_at'), table_name='device_history')
    op.drop_table('device_history')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_board_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_created_at'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_board_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_boards_status'), table_name='boards')
    op.drop_index(op.f('ix_boards_room_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_mac_address'), table_name='boards')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_home_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_home_members_user_id'), table_name='home_members')
    op.drop_index(op.f('ix_home_members_home_id'), table_name='home_members')
    op.drop_table('home_members')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_home_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_access_cards_id'), table_name='access_cards')
    op.drop_index(op.f('ix_access_cards_home_id'), table_name='access_cards')
    op.drop_index(op.f('ix_access_cards_card_uid'), table_name='access_cards')
    op.drop_table('access_cards')
    op.drop_index(op.f('ix_password_reset_otps_expires_at'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_email'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    op.drop_index(op.f('ix_homes_owner_id'), table_name='homes')
    op.drop_index(op.f('ix_homes_id'), table_name='homes')
    op.drop_table('homes')
    op.drop_index(op.f('ix_firmwares_is_active'), table_name='firmwares')
    op.drop_index(op.f('ix_firmwares_id'), table_name='firmwares')
    op.drop_index(op.f('ix_firmwares_board_type'), table_name='firmwares')
    op.drop_table('firmwares')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fcm_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
